name: Build userscript

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Container needs only basic repo content read permissions.
    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Use Node.js 12.x"
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint:all

      - name: Build userscript
        run: yarn userscript:release

      - name: Store userscript
        uses: actions/upload-artifact@v2
        with:
          name: userscript
          path: packages/userscript/bundle/kitten-scientists.user.js

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
